# SOLUTIONS AND EXPLANATIONS FOR LESSON 1: MATRIX FOR AI (20/6/2026) HOMEWORK - USING TEXTS

## PREPARATION FOR BOTH EXERCISES: TRANSFORM TEXTS TO VECTORS AND MATRIXES

Import numpy lib and create a list of 8 sentences to transform to vectors

In [6]:
import numpy as np
sentence = ["i love you", 
            "this house is big",
            "you are beautiful",
            "that will do",
            "you are welcome", 
            "how are you", 
            "what is your name", 
            "i play badminton"]

extract each separate word from every sentence and then sort them in alphabet order

In [11]:
word = []
for s in sentence:
    for w in s.lower().split():
        word.append(w)
word.sort()
print(word)

['are', 'are', 'are', 'badminton', 'beautiful', 'big', 'do', 'house', 'how', 'i', 'i', 'is', 'is', 'love', 'name', 'play', 'that', 'this', 'welcome', 'what', 'will', 'you', 'you', 'you', 'you', 'your']


building a function to transform these words to vectors

In [24]:
def to_vectors(s):
    v = np.zeros(len(word)) # an array all 0 with length of word list above
    for w in s.lower().split():
        v[word.index(w)] += 1 
    return v
matrix = np.array([to_vectors(s) for s in sentence], dtype=int)
print(matrix)
print(matrix.shape)

[[0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]]
(8, 26)


Here, 8 sentences are separately transformed to 8 vectors (each with 26 dims or 26 words in total) which makes a 8x26 matrix.
- 8 rows are 8 sentences whose "1" stands at the index corresponds to a word in the sorted word list above
- Each column represents the frequency that each word appears in each sentence. for ex, the first column represents for word[0] ('are') that 'are' appears in sentence 3,5 and 6 one time.

## EXERCISE 1: CALCULATE THE SIMILARITY

Basic operation: broadcasting